site_name: AI Sandbox Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Conventions:
    - Coding: conventions/coding.md
    - Documentation: conventions/documentation.md
    - Project: conventions/project.md
    - CraftGraph: CraftGraph/conventions.md
  - Process: process.md
  - CraftGraph:
    - Overview: CraftGraph/overview.md
    - MVP Plan: CraftGraph/mvp_plan.md
    - Completed Tasks: CraftGraph/completed_tasks.md
    - Current Status: CraftGraph/current_status.md